name: ecommerce_shop
description: "A new Flutter project."
publish_to: 'none' # This prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cloud_firestore: ^5.6.9
  crypto: ^3.0.7
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.7
  firebase_app_check: ^0.3.2+9
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_image_compress: ^2.4.0
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.3.1
  model_viewer_plus: ^1.7.0
  provider: ^6.1.5
  random_string: ^2.3.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  webview_flutter: ^4.13.0
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/1.jpg
    - lib/assets/images/3.jpg
    - lib/assets/images/white.png
    - images/products/headphone.png
    - images/icons/google.png
    - images/products/laptop.png
    - images/products/tv.png
    - images/products/watch.png
    - images/listings/headphone.png
    - images/login.json
    - images/fallback.json
    - images/emptyCart.json
    - images/error.json
    - images/shopping1.json
    - images/maintenance.json
    - images/shopping2.json
    - images/emptyOrders.json
    - images/shopping3.json
    - lib/assets/images/default_profile.png
    - lib/assets/images/application_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/application_icon.png"
